# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='BusinessType',
            field=models.CharField(choices=[('S', 'Supermarket'), ('F', 'Farm'), ('P', 'Produce Stall'), ('Pi', 'Private Individual'), ('Re', 'Restaurant')], default='S', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='CompanyAddress',
            field=models.CharField(default='ok', max_length=255, verbose_name='Business Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='CompanyName',
            field=models.CharField(default='ok', max_length=255, verbose_name='Name of Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ContactName',
            field=models.CharField(default='ok', max_length=255, verbose_name='Name of Contact Person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='OtherInfo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Other Info'),
        ),
    ]
