# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180217_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Contact'),
        ),
    ]
