# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 02:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='foodtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Post Date')),
                ('collectdate', models.DateTimeField(verbose_name='Collect By Date')),
                ('address', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('quality', models.CharField(blank=True, max_length=300, null=True)),
                ('foodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.foodtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='postlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('quality', models.CharField(blank=True, max_length=300, null=True)),
                ('foodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.foodtype')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
