# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 15:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodwaste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Post Date')),
                ('address', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('foodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.foodtype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
