# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_foodwaste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodwaste',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
